### ISSUE TITLE
Doesn't work at all for me

### ISSUE THREAD

**Issue by argon932** [Kruk2/VamRepacker#1]
Tried clean install of the last 2 versions (making sure there's no cache). Running as admin on Win11. I add my VAM and VARs REPO directories. I scan. It scans everything. No errors.

Directories are setup as:
C:/Virt-A-Mate
C:/Virt-A-Mate/BACKUP/VAR Database

I setup a profile to always add certain VARs, I enable the profile and click the soft link selected profile button. 0 files copied.
I manually move a VAR to VAM directory and click search for missing dependencies in VAM and softlink. 0 files copied.

Checking move files instead of doing soft link, then clicking search for missing dependencies. 0 files copied.

Dry run is not checked.

Spent 2 hours on it and couldn't figure out why it doesn't work for me.

**Comment by Kruk2** [comment]
I didn't really test it on Win11 but it should work fine.
Try to manually move a VAR to VAM directory and click "search for missing dependencies". After that new log files will be created.
Could you send me:
copy_missing_deps_from_repo.log
var_scan.log
scan_json_files.log

Ideally perform the test using a clean VAM installation and minimal REPO. For example copy look to VAM and in REPO keep only dependencies you know it needs (like hair, clothes, morphs).
It will be easier to narrow down the issue.

**Comment by argon932** [comment]
I did that and just copied a VAR that simply requires MacGruber.Life.12.

copy_missing_deps_from_repo.log is empty
**logs removed**

If this isn't enough i'll try a barebones brand new VAM installation and only a couple VARs in a REPO. I do see some errors in there due to corrupt VARs in my repo so maybe those are totally stopping the program from working.

**Comment by Kruk2** [comment]
I'm not sure if I see it correctly but is your REPO directory inside VAM?
I think it might be the issue.
Could you move your REPO outside VAM dir and test again?

**Comment by argon932** [comment]
Ha! Something so simple I should have tested that.

Moving the REPO outside of the VAM install fixed it. Thanks :)

**Comment by Kruk2** [comment]
Glad it worked, I will add extra validation in next release to make sure REPO is outside VAM (and VAM is outside REPO).

**Comment by argon932** [comment]
I spoke too soon. The problem came back but I think I know what it is. It's caused by a corrupt VAR file. I'll provide more details in a bit.

**Comment by Kruk2** [comment]
Corrupted var shouldn't prevent VamToolbox from doing it's job (unless that corrupted var is meant to be softlinked)

**Comment by argon932** [comment]
I figured it out, two different things were breaking it making it harder to troubleshoot.

This is what I am using now:
C:/Games/VAM
C:/Games/VARs

This is what I was using:
C:/Games/Virt-A-Mate
C:/Games/Virt-A-Mate VARs

So either - and/or spaces in the filepath breaks the code. Also, the REPO must not be in the VAM folder either because putting it back in there even with the fixed paths breaks it once again.

I'll mess with it more later and if the issue comes back i'll let you know.

EDIT: This also works, so it must be spaces in the last folder name breaking it.
C:/Games/Virt-A-Mate/VAM
C:/Games/Virt-A-Mate/VARs

**Comment by Kruk2** [comment]
Yep, I think it's a bug.
As long as them REPO directory doesn't start with VAM directory it will work fine:
**C:/Games/Virt-A-Mate**
**C:/Games/Virt-A-Mate** VARs

breaks but this:
C:/Games/Virt-A-Mate
C:/Games/Virt-A-MatXe VARs

should work, you can test that if you want.
Spaces shouldn't matter

**Comment by argon932** [comment]
Confirmed.

Works:
C:\Games\Virt-A-Mate\VAM
C:\Games\Virt-A-Mate\VAXM VARs

Doesn't Work:
C:\Games\Virt-A-Mate\VAM
C:\Games\Virt-A-Mate\VAM VARs

Probably the same bug that is making it not work when the REPO is inside the VAM directory.

Also, would it be possible to add a "Remove all soft links" button? Currently I just select remove all soft-links before applying profile, and apply no profiles to do it.
