### ISSUE TITLE
Symlinks inside VAM folder causes error

### ISSUE THREAD

**Issue by scsi111** [Kruk2/VamRepacker#3]
Plugin JayJayWon.BrowserAssist(Free).10.var
[](https://hub.virtamate.com/resources/browserassist-free.20134/)
Requires to create symlinks inside
**..\Saves\PluginData\JayJayWon\BrowserAssist\SymLinks\** folder, leading to 
**AddonPackages
AddonPackagesFilePrefs
Custom
Saves** yes, a loop, I know.
If these symlinks are present, then VamToolbox 0.11.8.0 spits out Unhandled Thread Exception during Scanning and progress animation just goes indefinately.
![image](https://user-images.githubusercontent.com/76934000/193443650-fc7c7af1-ea62-44d1-920a-0c903ba38c5e.png)

**Comment by Kruk2** [comment]
Could you try 0.12.0? Looks a bit like an error from framework and not from my code.
If it still happens could you check if the .json.hide actually exists (and the file it points to also exists?)

// edit
fixed in https://github.com/Kruk2/VamToolbox/releases/tag/0.12.1
