### ISSUE TITLE
Fix RG Morphs in JSON files under saves

### ISSUE THREAD

**Issue by gilberti69** [Kruk2/VamRepacker#4]
Is it possible to fix the RG virus morphs in JSON files under saves as this only seems to work for VAR files.  I run VAM unpacked.

Thanks

**Comment by Kruk2** [comment]
Possible but way too complied. Probably better solution would be to scan unpacked vars which is currently not supported now.

**Comment by gilberti69** [comment]
NP, I have written a script to do that now anyway. thanks for the reply
