### ISSUE TITLE
Can you make a dependencies text fixing feature？

### ISSUE THREAD

**Issue by vvidlee** [Kruk2/VamRepacker#5]
Replace the list of dependencies in meta.json with the actual referenced dependencies scanned, instead of just removing all of it, like a dependency normalization feature. It is also equivalent to storing dependences scan results in meta, so that you only need to scan once, even if the first time takes a long time. I'd appreciate it a lot if you'd consider it. The toolbox is really great.

**Comment by Kruk2** [comment]
Technically it's possible but what's the use case here?
The only thing that comes to my mind is preparing var for publishing i.e. you want to correctly set the dependencies.

**Comment by vvidlee** [comment]
Thank you for your reply. I just think that a var with accurate dependency information is more perfect，you can check it at any time.  Some of the dependency information generated by VAM packaging is inaccurate and more than mod actually needs.  It's my little suggestion，I think a lot of people will like this feature.

**Comment by vvidlee** [comment]
Happy lunar new year！
