### ISSUE TITLE
VAR versioning issues

### ISSUE THREAD

**Issue by JexxTay** [Kruk2/VamRepacker#6]
Hi, first off, really love the tool, couldn't use VAM without it.

Issue dependencies that list a specific version for example "MacGruber.LogicBricks.12.var" but you have only version "MacGruber.LogicBricks.14.var", an "Unresolved references" entry is generated even though the reference exists in the newer version.

This could be handled in two ways, a "Var fixers" option to change versions to ".latest" or have Vam Toolbox use a higher reference if exists (which is what VAM does).

My current workaround is a folder full of VARs that are scripts that is always linked in profiles, which kind of spoils the "only what's needed" function of VamToolbox.

**Comment by Kruk2** [comment]
Thanks!

This one is quite interesting. So you're saying that VAM will resolve script from version .14 even is scene is hardcoded to use .12?
If that's true then definitely vamToolbox should follow the same logic and link higher version.
I wonder if there is some kind of a setting for it? Does it only work for scripts or all resources?
Could you share var that does this (or a name of a var)?

**Comment by JexxTay** [comment]
If you have both version .12 and version .14 it will use .12 if hard coded to .12.
If you have both version .12 and version .14 it will use .14 if hard coded to .latest.
If you have only version .14 it will use .14 even if hard coded to .12.

I believe that it will even load an older version than hardcoded if that is the only one available (not tested).

This is true of all "packages" as VAM calls them.

Take any VAR that uses external VAR resource and rename the external resource to a different version and you should this happen. 

Hope that helps, if not let me know.

**Comment by Kruk2** [comment]
Fixed in 0.12.2.
VamToolbox will now use latest available version when exact match doesn't exist.
