### ISSUE TITLE
Missing deps and softlink produces always an error at end

### ISSUE THREAD

**Issue by femdogg** [Kruk2/VamRepacker#8]
Missing deps and softlink produces always an error at end:

![image](https://github.com/user-attachments/assets/f8c1eadf-55c3-480c-860e-de14c9f34e46)

**Comment by Kruk2** [comment]
Select 
![image](https://github.com/user-attachments/assets/5deaf34b-8455-4592-8363-e1ae9f14c4cb)
mode to SoftLink

**Comment by femdogg** [comment]
Thanks this worked!!
